import re

with open('index.html', 'r', encoding='utf-8') as f:
    content = f.read()

# Very rudimentary replacement just for the requested English version
replacements = {
    'lang="el"': 'lang="en"',
    'Άννα Γιακουμάκη — Χημικός | Πανεπιστήμιο Κρήτης': 'Anna Giakoumaki — Chemist | University of Crete',
    'Ψηφιακό βιογραφικό & ακαδημαϊκό portfolio της Άννας Γιακουμάκη. Τεταρτοετής φοιτήτρια Χημείας (Τομέας Βιοχημείας) στο Πανεπιστήμιο Κρήτης.': 'Digital resume & academic portfolio of Anna Giakoumaki. Senior Chemistry student (Biochemistry) at the University of Crete.',
    'Άννα Γιακουμάκη': 'Anna Giakoumaki',
    'Προφίλ': 'Profile',
    'Δεξιότητες': 'Skills',
    'Εμπειρία': 'Experience',
    'Πιστοποιήσεις': 'Certifications',
    'Έργα': 'Projects',
    'Εθελοντισμός': 'Volunteering',
    'Επικοινωνία': 'Contact',
    '🇬🇧 EN': '🇬🇷 EL',
    'en.html': 'index.html',
    'Τμήμα Χημείας — Πανεπιστήμιο Κρήτης': 'Chemistry Department — University of Crete',
    'Άννα <em>Γιακουμάκη</em>': 'Anna <em>Giakoumaki</em>',
    'Τεταρτοετής Φοιτήτρια Χημείας · Τομέας Βιοχημείας': 'Senior Chemistry Student · Biochemistry Field',
    'Εξειδίκευση σε Αναλυτική Χημεία & Ποιοτικό Έλεγχο Τροφίμων — HPLC, GC-MS, ESI-MS — Πρακτική Άσκηση στην Ανάλυση Ελαιολάδου': 'Specialization in Analytical Chemistry & Food Quality Control — HPLC, GC-MS, ESI-MS — Internship in Olive Oil Analysis',
    'cv-greek.pdf': 'cv-english.pdf',
    'Anna_Giakoumaki_CV_GR.pdf': 'Anna_Giakoumaki_CV_EN.pdf',
    'Λήψη CV': 'Download CV',
    'Μάθετε περισσότερα': 'Learn more',
    'Μέσος Όρος<br>Βαθμολογίας': 'GPA',
    'Υπότροφος<br>Εργαζάκειου Ιδρ.': 'Ergazakeio<br>Scholarship',
    'Βραβείο<br>UNESCO 2023': 'Prize<br>UNESCO 2023',
    'Πιστοποιήσεις<br>& Σεμινάρια': 'Certifications<br>& Seminars',
    'Ακαδημαϊκό Προφίλ': 'Academic Profile',
    'Σχετικά με Εμένα': 'About Me',
    'Φοιτώ στο <strong>Τμήμα Χημείας</strong> του Πανεπιστημίου Κρήτης με κατεύθυνση στον Τομέα <strong>Βιοχημείας</strong>. Διατηρώ υψηλή ακαδημαϊκή επίδοση (Μ.Ο. <strong>7.44/10</strong>) με εκτεταμένη εργαστηριακή τριβή σε όλους τους βασικούς κλάδους της Χημείας.': 'I am a <strong>Chemistry Student</strong> at the University of Crete, specializing in <strong>Biochemistry</strong>. I maintain a high academic performance (GPA <strong>7.44/10</strong>) with extensive laboratory experience across all major fields of Chemistry.',
    'Υποτροφία & Διακρίσεις': 'Scholarships & Awards',
    '4ετής υποτροφία Εργαζάκειου Ιδρύματος (γραπτός διαγωνισμός). 1ο Βραβείο 12ου Διεθνούς Λογοτεχνικού Διαγωνισμού UNESCO (2023). Απολυτήριο Λυκείου: <strong>19.9/20</strong>.': '4-year Ergazakeio Foundation Scholarship. 1st Prize at the 12th International Literary Competition UNESCO (2023). High School Diploma with Honors: <strong>19.9/20</strong>.',
    'Πρακτική Άσκηση': 'Internship',
    '3μηνη πρακτική στη <strong>Σαβουϊδάκης Α.Ε.</strong> (Ιουλ.–Σεπ. 2025): ανάλυση ελαιολάδου, φυσικοχημικές δοκιμές, ποιοτικός έλεγχος τροφίμων.': '3-month internship at <strong>Savoidakis S.A.</strong> (Jul.–Sep. 2025): olive oil analysis, physicochemical testing, and food quality control.',
    'Γλώσσες & Λογισμικό': 'Languages & Software',
    'Αγγλικά B2 (επερχόμενη C2) · OriginLab · ChemDraw · MS Office': 'English B2 (upcoming C2) · OriginLab · ChemDraw · MS Office',
    'Εργαστηριακή Εμπειρία': 'Laboratory Experience',
    'Εργαστηριακές Δεξιότητες': 'Laboratory Skills',
    'Επιλέξτε κλάδο χημείας για να δείτε αναλυτικά τις τεχνικές.': 'Select a chemistry field to see detailed techniques.',
    'Όλοι οι Κλάδοι': 'All Fields',
    'Οργανική': 'Organic',
    'Αναλυτική': 'Analytical',
    'Ανόργανη': 'Inorganic',
    'Βιοχημεία': 'Biochemistry',
    'Φυσικοχημεία': 'Physical Chemistry',
    'Οργανική Χημεία': 'Organic Chemistry',
    'Οκτ 2023 – Ιουν 2024': 'Oct 2023 – Jun 2024',
    'Ανακρυστάλλωση & Εκχύλιση': 'Recrystallization & Extraction',
    'Κλασματική Απόσταξη': 'Fractional Distillation',
    'Χρωματογραφία Λεπτής Στοιβάδας (TLC)': 'Thin Layer Chromatography (TLC)',
    'Χρωματογραφία Στήλης': 'Column Chromatography',
    'Αναλυτική Χημεία': 'Analytical Chemistry',
    'Φεβ 2024 – Δεκ 2024': 'Feb 2024 – Dec 2024',
    'Προσδιορισμός Pka & Αγωγιμομετρία': 'Pka Determination & Conductometry',
    'Ανάλυση Κρασιών & Ελαιόλαδου': 'Wine & Olive Oil Analysis',
    'Ανάλυση Ιόντων K⁺ στο Νερό & Πολαρογραφία': 'Analysis of K⁺ ions in Water & Polarography',
    'Φασματομετρία Μάζας ESI-MS': 'ESI-MS Mass Spectrometry',
    'Ανόργανη Χημεία': 'Inorganic Chemistry',
    'Οκτ 2024 – Απρ 2025': 'Oct 2024 – Apr 2025',
    'Μελέτη Φασμάτων IR & UV-VIS': 'Study of IR & UV-VIS Spectra',
    'Ανάλυση Διαγραμμάτων SEM & XRD': 'Study of SEM & XRD Diagrams',
    'Σύνθεση MOF (Metal-Organic Frameworks)': 'MOF Synthesis (Metal-Organic Frameworks)',
    'Φεβ 2025 – Ιουν 2025': 'Feb 2025 – Jun 2025',
    'Απομόνωση Χρωμοσωμικού DNA': 'Isolation of Chromosomal DNA',
    'Western Blot & Ηλεκτροφόρηση': 'Western Blot & Electrophoresis',
    'Ενζυμική Κινητική & Λειτουργία Ενζύμων': 'Enzyme Kinetics & Function',
    'Μελέτη Φυτικών Χρωστικών': 'Study of Plant Pigments',
    'Οκτ 2023 – Ιουν 2025': 'Oct 2023 – Jun 2025',
    'Θερμιδομετρία & Διαγράμματα Φάσεων': 'Calorimetry & Phase Diagrams',
    'Κινητική Αντιδράσεων (UV-Vis)': 'Reaction Kinetics (UV-Vis)',
    'Ηλεκτροχημεία (ΗΕΔ, Αγωγιμότητα)': 'Electrochemistry (EMF, Conductivity)',
    'Φασματοσκοπία IR & UV-Vis': 'IR & UV-Vis Spectroscopy',
    'Ακαδημαϊκή Πορεία': 'Academic Journey',
    'Εκπαίδευση & Πρακτική': 'Education & Internship',
    'Οκτ 2022 – Σήμερα': 'Oct 2022 – Present',
    'Ηράκλειο Κρήτης — Τομέας Βιοχημείας': 'Heraklion, Crete — Biochemistry Field',
    'Μ.Ο. Βαθμολογίας: <strong>7.44/10</strong> (ως 11/02/2026). Εκτεταμένη εργαστηριακή εκπαίδευση σε 5 κλάδους χημείας.': 'GPA: <strong>7.44/10</strong> (as of 11/02/2026). Extensive lab training across 5 chemistry fields.',
    'Ιουλ 2025 – Σεπ 2025 (3 μήνες)': 'Jul 2025 – Sep 2025 (3 months)',
    'Πρακτική Άσκηση · Σαβουϊδάκης Α.Ε.': 'Internship · Savoidakis S.A.',
    'Αγία Βαρβάρα, Ηράκλειο Κρήτης': 'Agia Varvara, Heraklion',
    'Ανάλυση ελαιολάδου & ποιοτικός έλεγχος. Φυσικοχημικές δοκιμές και εργαστηριακά πρωτόκολλα βιομηχανικής διασφάλισης ποιότητας.': 'Olive oil analysis & quality control. Physicochemical tests and industrial quality assurance lab protocols.',
    'Ποιοτικός Έλεγχος': 'Quality Control',
    'Ελαιόλαδο': 'Olive Oil',
    'Τετραετής Υποτροφία Εργαζάκειου Ιδρύματος': '4-Year Ergazakeio Foundation Scholarship',
    'Κατόπιν γραπτού διαγωνισμού στο μάθημα της Έκθεσης.': 'Awarded after a written essay competition.',
    '1ο Βραβείο · 12ος Διεθνής Λογοτεχνικός Διαγωνισμός UNESCO': '1st Prize · 12th International Literary Competition UNESCO',
    'Πρώτο βραβείο στον 12ο Διεθνή Λογοτεχνικό Διαγωνισμό του Ομίλου UNESCO Λόγου, Τεχνών & Επιστημών Ελλάδος.': 'First prize in the 12th International Literary Competition by the UNESCO Club for Literature, Arts, and Sciences of Greece.',
    'Απολυτήριο Λυκείου · Άριστα (19.9/20)': 'High School Diploma · Honors (19.9/20)',
    'Γενικός Βαθμός Απολυτηρίου: 19.9/20.': 'Overall GPA: 19.9/20.',
    'Εξειδίκευση': 'Specialization',
    'Πιστοποιήσεις & Σεμινάρια': 'Certifications & Seminars',
    'Πιστ/κό:': 'Cert. No:',
    'ΚΑΡΠΑ / BLS': 'BLS / CPR',
    'Διδάσκοντας την κλιματική αλλαγή στη δευτεροβάθμια εκπαίδευση': 'Teaching Climate Change in Secondary Education',
    'Σύγχρονες Εργ. Μέθοδοι': 'Modern Lab Methods',
    'Αναλυτική Χημεία — ΚΔΒΜ Τσαούση': 'Analytical Chemistry — KEDIVIM Tsaousi',
    'Ανθρωποκεντρική ΤΝ': 'Human-Centered AI',
    'Στην Εκπαίδευση — Ε.ΔΙ.Β.Ε.Α., Πανεπιστήμιο Κρήτης': 'In Education — E.DI.B.E.A., University of Crete',
    'Επιλεκτική Αλαλία': 'Selective Mutism',
    'Ενίσχυση συμμετοχής παιδιών στο σχολικό περιβάλλον (ΕΣΕΑΛ)': 'Enhancing participation of children in school (ESEAL)',
    'Έρευνα & Διάχυση': 'Research & Outreach',
    'Projects & Επιστημονική Δράση': 'Projects & Scientific Activity',
    'Ερευνητική Εργασία': 'Research Project',
    'Θεωρητική ανάλυση μεθόδων ανίχνευσης νοθείας σε δείγματα μελιού': 'Theoretical analysis of honey adulteration detection methods',
    'Νοέμβριος 2023 · Αναλυτική Χημεία I': 'November 2023 · Analytical Chemistry I',
    'Υπεύθυνη Καθηγήτρια: <strong>Χατζηιωάννου Χρυσοβαλάντου-Αναστασία</strong>, Πανεπιστήμιο Κρήτης.': 'Supervising Professor: <strong>Chatziioannou Chrysovalantou-Anastasia</strong>, University of Crete.',
    'Κατανομή ταχυτήτων Maxwell-Boltzmann': 'Maxwell-Boltzmann speed distribution',
    'Νοέμβριος 2023 · Εργ. Φυσικοχημείας I': 'November 2023 · Physical Chemistry Lab I',
    'Υπεύθυνος: <strong>Παπαδημητρίου Βασίλειος</strong>, Πανεπιστήμιο Κρήτης.': 'Supervisor: <strong>Papadimitriou Vasileios</strong>, University of Crete.',
    '100 Χρόνια Ε.Ε.Χ. — Πειράματα για παιδιά': '100 Years of AGC — Chemistry Experiments for children',
    '28 Σεπ 2024 · Κ.Α.Μ., Χανιά': '28 Sep 2024 · CAM, Chania',
    'Παρουσίαση πειραμάτων χημείας για παιδιά με την εθελοντική ομάδα <strong>COG</strong>.': 'Chemistry experiments presentation for children with the <strong>COG</strong> volunteer team.',
    'Πανελλήνια Ημέρα Χημείας — Βιωματικό Εργαστήριο': 'Panhellenic Chemistry Day — Experiential Workshop',
    '9 Μαρ 2025 · Άγιος Νικόλαος': '9 Mar 2025 · Agios Nikolaos',
    'Εθελοντική ομάδα COG & Ε.Ε.Χ. — Πειράματα & βιωματικό εργαστήριο.': 'COG volunteer team & AGC — Experiments & experiential workshop.',
    '2η Γιορτή «Χαμόγελο του Παιδιού» — Ρέθυμνο': '2nd "Smile of the Child" Festival — Rethymno',
    '20 Σεπ 2025 · Ρέθυμνο': '20 Sep 2025 · Rethymno',
    'Διαδραστικά πειράματα χημείας με την ομάδα COG στο Χαμόγελο του Παιδιού.': 'Interactive chemistry experiments with COG at Smile of the Child.',
    'Εκπρόσωπος Σαβουϊδάκης Α.Ε. — Ημέρα Καριέρας UOC': 'Savoidakis S.A. Representative — UOC Career Day',
    '31 Οκτ 2025 · Ηράκλειο Κρήτης': '31 Oct 2025 · Heraklion, Crete',
    'Ειδικός συνεργάτης & εκπρόσωπος στην Ημέρα Καριέρας 2025 του Πανεπιστημίου Κρήτης.': 'Special associate & representative at the 2025 Career Day of the University of Crete.',
    'Κοινωνική Προσφορά': 'Social Contribution',
    'Εθελοντισμός & Ηγεσία': 'Volunteering & Leadership',
    'Πανεπιστήμιο Κρήτης · 2023 – Σήμερα': 'University of Crete · 2023 – Present',
    'Ενεργό μέλος της εθελοντικής ομάδας COG. Ανάδειξη εφαρμογών χημείας στην κοινωνία μέσω διαδραστικών πειραμάτων.': 'Active member of the COG volunteer group. Highlighting chemistry applications in society via interactive experiments.',
    'Επιχειρησιακός συντονισμός εθελοντών, logistics & άμεση επίλυση οργανωτικών προκλήσεων για <strong>200+ συμμετέχοντες</strong>.': 'Operational coordination of volunteers, logistics & real-time problem solving for <strong>200+ participants</strong>.',
    'Ημέρα Καριέρας UOC 2025': 'UOC Career Day 2025',
    'Πλήρης συντονισμός & εκπαίδευση εθελοντών. Κεντρικός σύνδεσμος μεταξύ διοίκησης, εθελοντών & εκπροσώπων εταιρειών.': 'Full coordination & training of volunteers. Primary liaison between administration, volunteers & company representatives.',
    'Ανακύκλωση Τηγανέλαιων': 'Waste Oil Recycling',
    '3ο ΓΕΛ Αλεξανδρούπολης · 2019 – 2021': '3rd High School of Alexandroupoli · 2019 – 2021',
    'Περιβαλλοντική ομάδα συλλογής χρησιμοποιημένων τηγανέλαιων για ανακύκλωση & παραγωγή biodiesel.': 'Environmental group for waste oil collection for recycling & biodiesel production.',
    'Ακαδημαϊκή Υποστήριξη': 'Academic Support',
    'Συστάσεις': 'Recommendations',
    'Κουβαράκης Αντώνιος': 'Kouvarakis Antonios',
    'Τομέας Οργανικής Χημείας': 'Organic Chemistry Division',
    'Παπαδημητρίου Βασίλειος': 'Papadimitriou Vassilis',
    'Τομέας Φυσικοχημείας': 'Physical Chemistry Division',
    'Χατζηιωάννου Χρ.-Αναστασία': 'Chatziioannou Chr.-Anastasia',
    'Τομέας Αναλυτικής Χημείας': 'Analytical Chemistry Division',
    'Ελάτε σε Επαφή': 'Get in Touch',
    'Μη διστάσετε να επικοινωνήσετε για ακαδημαϊκές ευκαιρίες, ερευνητικά projects ή επαγγελματικές προτάσεις.': 'Feel free to contact me for academic opportunities, research projects, or professional proposals.',
    'Τηλέφωνο': 'Phone',
    'Τοποθεσία': 'Location',
    'Ηράκλειο Κρήτης, Τ.Κ. 71202': 'Heraklion, Crete, 71202',
    'Νέο μήνυμα από το Portfolio σας!': 'New message from your Portfolio!',
    'Ονοματεπώνυμο': 'Full Name',
    'Π.χ. Μαρία Παπαδάκη': 'e.g. Maria Papadaki',
    'Θέμα': 'Subject',
    'Θέμα μηνύματος': 'Message Subject',
    'Μήνυμα': 'Message',
    'Γράψτε εδώ το μήνυμά σας...': 'Write your message here...',
    'Αποστολή': 'Send',
    'Τμήμα Χημείας, Πανεπιστήμιο Κρήτης': 'Chemistry Department, University of Crete',
    'Αρχική': 'Home',
    'Εκτύπωση CV': 'Print CV',
    'Εκτύπωση / Αποθήκευση CV': 'Print / Save CV',
    'Άννα Γιακουμάκη · Τμήμα Χημείας, Πανεπιστήμιο Κρήτης': 'Anna Giakoumaki · Chemistry Department, University of Crete'
}

for k, v in replacements.items():
    content = content.replace(k, v)

with open('en.html', 'w', encoding='utf-8') as f:
    f.write(content)

print("Translated successfully to en.html")
